# Generated by Django 4.2.15 on 2024-09-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto Perfil', null=True, upload_to=''),
        ),
    ]
