# Generated by Django 4.2.15 on 2024-10-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', help_text='Estado actual de la tarea', max_length=50),
        ),
    ]
